$ErrorActionPreference = "Stop"

$baseUrl = "http://localhost:1310/api/v1"

Write-Host "--- TEST: Register New Inactive User ---"
$rand = Get-Random -Maximum 9999
$testEmail = "testuser$rand@test.com"
$registerBody = @{
    email           = $testEmail
    password        = "Welcome1!"
    confirmPassword = "Welcome1!"
} | ConvertTo-Json

try {
    $regResponse = Invoke-RestMethod -Uri "$baseUrl/users" -Method Post -Body $registerBody -ContentType "application/json"
    Write-Host "Registration Success. Sent confirm email to: $($regResponse.email)"
}
catch {
    Write-Host "Register Failed: $($_.Exception.Message)"
    if ($_.Exception.Response) {
        $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
        Write-Host "Response Body: $($reader.ReadToEnd())"
    }
}

Write-Host "`n[!ACTION REQUIRED] Check the background command terminal for the mocked `SmtpEmailService` logs to retrieve the 6-digit confirmation code...`n"

Write-Host "--- TEST: Submit Verification Code (Automated via SQLite extraction) ---"
$getCodeQuery = "SELECT TokenHash FROM VerificationTokens WHERE IsUsed = 0 ORDER BY Id DESC LIMIT 1;"
# We cannot reverse the BCrypt hash from the DB natively in power shell!
Write-Host "NOTE: The actual email service contains the plaintext token. Because we hashed the Token in the Database directly, an automated plaintext verification extraction from the mock server is complex.`n"

# In lieu of finding the exact code generated by the console, we will attempt the Login step directly to verify the account is correctly blocked.
$loginBody = @{
    email    = $testEmail
    password = "Welcome1!"
} | ConvertTo-Json

Write-Host "--- TEST: Login As Inactive User (Should Fail) ---"
try {
    $loginResponse = Invoke-RestMethod -Uri "$baseUrl/sessions" -Method Post -Body $loginBody -ContentType "application/json"
    Write-Host "Login Unexpectedly Succeeded!"
}
catch {
    Write-Host "Login Failed Successfully! Expected behavior. Account is Inactive."
    if ($_.Exception.Response) {
        $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
        Write-Host "Response Body: $($reader.ReadToEnd())"
    }
}
